[package]
name = "CoffeeShop"
version = "0.0.1"

[addresses]
coffee_shop = "0x1" # This is a placeholder and will be replaced with your address at publish time

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }